name = "fixed-staking-rewards"
version = "1.0.0"
description = "Fixed staking rewards contract for ERC20 tokens"

[var.main]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
rewardsToken = "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9"
stakingToken = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
rewardsTokenFeed = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[deploy.FixedStakingRewards]
artifact = "FixedStakingRewards"
args = [
    "<%= settings.owner %>",
    "<%= settings.rewardsToken %>", 
    "<%= settings.stakingToken %>",
    "<%= settings.rewardsTokenFeed %>",
]
